/* eslint-disable @typescript-eslint/quotes */
/* eslint-disable @typescript-eslint/member-ordering */
/* eslint-disable @typescript-eslint/naming-convention */
import { ComponentRef } from '@ionic/core/dist/types/interface';

export interface DynamicComponent<T extends ComponentRef = ComponentRef> {
  id?: number;
  title?: string;
  image?: string;
  component?: any | T;
  type?: string;
  order?: number;
  status?: any;
  created_at?: string;
  updated_at?: string;
  [key: string]: any;
}

export interface AuthReturnInfo {
  [key: string]: any;
}
export interface ErrorReturnInfo {
  [key: string]: any;
}
export interface AnyInfo {
  [key: string]: any;
}
export interface UserData{
  [key: string]: any;
}



// Generated by https://quicktype.io

export interface OneSignalNotificationData {
  notification?: Notification;
  action?: Action;
  [key: string]: any;
}

export interface Action {
  [key: string]: any;
}

export interface Notification {
  shown?: boolean;
  payload?: Payload;
  isAppInFocus?: boolean;
  displayType?: number;
  [key: string]: any;
}

export interface Payload {
  rawPayload?: RawPayload;
  additionalData?: Action;
  subtitle?: string;
  title?: string;
  sound?: string;
  body?: string;
  notificationID?: string;
  actionButtons?: any[];
  [key: string]: any;
}

export interface RawPayload {
  aps?: Aps;
  att?: Att;
  custom?: Custom;
  [key: string]: any;
}

export interface Aps {
  alert?: Alert;
  "mutable-content"?: number;
  sound?: string;
  [key: string]: any;
}

export interface Alert {
  subtitle?: string;
  title?: string;
  body?: string;
  [key: string]: any;
}

export interface Att {
  id?: string;
  [key: string]: any;
}

export interface Custom {
  a?: Action;
  i?: string;
  [key: string]: any;
}
